name: Basic Deploy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Copy files to gh-pages branch
        run: |
          # Fix HTML paths
          find . -name "*.html" -type f | xargs sed -i 's|href="/|href="./|g'
          find . -name "*.html" -type f | xargs sed -i 's|src="/|src="./|g'
          
          # Add base tags where needed
          for file in $(find ./games -name "index.html"); do
            sed -i 's|<head>|<head>\n  <base href="../../">|' "$file"
          done
          
          for file in $(find . -maxdepth 1 -name "*.html"); do
            sed -i 's|<head>|<head>\n  <base href="./">|' "$file"
          done
          
          # Configure Git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Create orphan branch
          git checkout --orphan gh-pages
          
          # Add all content
          git add .
          
          # Commit changes
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages
