name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Create .nojekyll
        run: touch .nojekyll
          
      - name: Make paths relative
        run: |
          # Find files to process
          find . -type f -name "*.html" | while read file; do
            # Skip files in node_modules, .git, etc.
            if [[ $file == *"node_modules"* ]] || [[ $file == *".git"* ]]; then
              continue
            fi
            
            # Replace absolute paths with relative ones
            sed -i 's|href="/|href="./|g' "$file"
            sed -i 's|src="/|src="./|g' "$file"
            
            # Add base tag if it doesn't exist and if it's a game file
            if [[ $file == *"/games/"* ]] && ! grep -q "<base href=" "$file"; then
              sed -i 's|<head>|<head>\n  <base href="../../">|' "$file"
            elif ! grep -q "<base href=" "$file"; then
              sed -i 's|<head>|<head>\n  <base href="./">|' "$file"
            fi
            
            echo "Processed $file"
          done
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
